// drxmldt.cpp is the code for dcl XML dita element props, JHG
// Copyright (c) 2008 by Omni Systems, Inc.  All rights reserved.

#include "dcappl.h"
#include "dcctlg.h"
#include "dcfili.h"
#include "dcfilp.h"
#include "dctxfx.h"
#include "dcfmtr.h"
#include "dcini.h"
#include "dcelem.h"
#include "drxml.h"
#ifdef DITA
#include "expat.h"
#endif
#ifdef UDOC
#include "mxlparser.h"
#include "drxmlud.h"
#endif
#include "drxmlfl.h"


/*
 epRoot = 1, epMap, epTopic, epTask, epMeta,
 epText, epInline, epPern, epPre, epTypo,
 epFig, epImage, epObj, epAlt, epParam,
 epTable, epTabRow, epTabCol, epTabCell,
 epTabHead, epTabBody, epTabStart,
 epLink, epKey, epRef, epRel, epXRsrc, epGroup, epSeq,
 epList, epListItem, epNumbered,
 epDefList, epDefEntry, epDefTerm, epDefDef,
 epParmList, epParmEntry, epParmTerm, epParmDef, epNote,
 epIndex, epIndexStart, epIndexSee, epIndexSeeAlso, epIndexSort,
 epTitle, epBkTitle, epSect, epFtn, epDesc,
 epNavtitle, epSDesc, epAbstr, epVar,
 epRefer, epGloss, epData, epCascadeItem, epCascadeSet, epSub,
 epTmark, epDraft, epAbbr, epNonum, epNolev
*/

etype **XMLrd::ElemTypes = NULL;

long XMLrd::ElemTypesCount = 0;

etype XMLrd::TopicElemTypes[TopicElemTypesCount] = {
 { "topic/term abbrev-d/abbreviated-form", 3, { epInline, epGloss, epAbbr }},  // *
 { "map/topicref bookmap/abbrevlist", 4, { epMap, epRef, epTopic, epList }},
 { "topic/abstract", 2, { epText, epAbstr }},
 { "topic/alt", 3, { epText, epInline, epAlt }},
 { "map/topicref bookmap/amendments", 4, { epMap, epRef, epTopic, epList }},
 { "map/anchor", 0, NULL},
 { "map/topicref mapgroup-d/anchorref", 3, { epMap, epRef, epTopic }},
 { "topic/keyword pr-d/apiname", 2, { epText, epInline }},
 { "map/topicref bookmap/appendices", 3, { epMap, epRef, epTopic }},  // *
 { "map/topicref bookmap/appendix", 3, { epMap, epRef, epTopic }},
 { "topic/data bookmap/approved", 0, NULL},
 { "topic/figgroup ut-d/area",  3, { epInline, epImage, epRef }},
 { "topic/audience", 0, NULL},
 { "topic/author", 2, { epText, epVar }},
 { "topic/ph hi-d/b", 3, { epText, epInline, epTypo }},
 { "map/topicref bookmap/backmatter", 2, { epMap, epList }},
 { "map/topicref bookmap/bibliolist", 4, { epMap, epRef, epTopic, epList }},
 { "topic/body", 2, { epText, epPern }},
 { "topic/bodydiv", 3, { epText, epSect, epNolev }},  // *
 { "map/topicref bookmap/bookabstract", 3, { epTopic, epMap, epRef }},
 { "topic/data bookmap/bookchangehistory", 0, NULL},  // *
 { "topic/data bookmap/bookevent", 0, NULL},
 { "topic/data bookmap/bookeventtype", 0, NULL},
 { "topic/data bookmap/bookid", 2, { epMap, epList }},
 { "topic/ph bookmap/booklibrary", 3, { epText, epInline, epMap }},
 { "map/topicref bookmap/booklist", 4, { epMap, epRef, epTopic, epList }},
 { "map/topicref bookmap/booklists", 2, { epMap, epList }},
 { "map/map bookmap/bookmap", 2, { epRoot, epMap }},
 { "map/topicmeta bookmap/bookmeta", 3, { epMap, epMeta, epTopic }},
 { "topic/data bookmap/booknumber", 3, { epText, epMap, epVar }},
 { "topic/data bookmap/bookowner", 3, { epText, epMap, epVar }},
 { "topic/data bookmap/bookpartno", 3, { epText, epMap, epVar }},
 { "topic/data bookmap/bookrestriction", 3, { epText, epMap, epVar }},
 { "topic/data bookmap/bookrights", 3, { epText, epMap, epVar }},
 { "topic/title bookmap/booktitle", 1, { epMap }},
 { "topic/ph bookmap/booktitlealt", 4, { epText, epMap, epVar, epBkTitle }},
 { "topic/boolean", 1, { epInline }},
 { "topic/brand", 2, { epText, epVar }},
 { "topic/category", 2, { epText, epVar }},
 { "map/topicref bookmap/chapter", 3, { epMap, epRef, epTopic }},
 { "topic/stentry  task/chdesc", 3, { epTask, epText, epTabCell }},
 { "topic/stentry  task/chdeschd", 3, { epTask, epText, epTabCell }},
 { "topic/sthead task/chhead", 3, { epTask, epTabRow, epTabHead }},
 { "topic/li task/choice", 5, { epTask, epText, epListItem, epXRsrc, epPern }},
 { "topic/ul task/choices", 3, { epTask, epList, epSub }},
 { "topic/simpletable task/choicetable", 3, { epTask, epTable, epStart }},
 { "topic/stentry  task/choption", 3, { epTask, epText, epTabCell }},
 { "topic/stentry  task/choptionhd", 3, { epTask, epText, epTabCell }},
 { "topic/strow task/chrow", 3, { epTask, epTabRow, epTabBody }},
 { "topic/cite", 2, { epText, epInline }},
 { "topic/ph task/cmd", 3, { epTask, epText, epInline }},
 { "topic/keyword sw-d/cmdname", 2, { epText, epInline }},
 { "topic/pre pr-d/codeblock", 2, { epText, epPre }},
 { "topic/ph pr-d/codeph", 3, { epText, epInline, epPre }},
 { "topic/xref pr-d/coderef", 3, { epText, epPre, epRef }},
 { "map/topicref bookmap/colophon", 3, { epMap, epRef, epTopic }},
 { "topic/colspec", 2, { epTable, epTabCol }},
 { "topic/ph bookmap/completed", 3, { epText, epMap, epInline }},
 { "topic/component", 2, { epText, epVar }},
 { "topic/body concept/conbody", 2, { epText, epPern }},
 { "topic/bodydiv concept/conbodydiv", 3, { epText, epSect, epNolev }},  // *
 { "topic/topic concept/concept", 1, { epRoot }},
 { "topic/section task/context", 3, { epTask, epText, epSect }},
 { "topic/ph ut-d/coords", 3, { epText, epImage, epGroup }},
 { "topic/data bookmap/copyrfirst", 0, NULL},
 { "topic/copyrholder", 2, { epText, epVar }},
 { "topic/copyright", 0, NULL},
 { "topic/data bookmap/copyrlast", 0, NULL},
 { "topic/copyryear", 0, NULL},
 { "topic/created", 0, NULL},
 { "topic/critdates", 0, NULL},
 { "topic/data", 3, { epData, epText, epInline }},
 { "topic/data-about", 2, { epData, epInline }},
 { "topic/ph bookmap/day", 3, { epText, epMap, epInline }},
 { "topic/dd", 3, { epText, epTabCell, epDefDef }},
 { "topic/ddhd", 3, { epText, epTabCell, epDefDef }},
 { "map/topicref bookmap/dedication", 3, { epMap, epRef, epTopic }},
 { "topic/ph pr-d/delim", 1, { epText }},
 { "topic/desc", 2, { epText, epDesc }},
 { "dita", 0, NULL},
 { "topic/dl", 3, { epTable, epStart, epDefList }},
 { "topic/dlentry", 3, { epTabRow, epTabBody, epDefEntry }},
 { "topic/dlhead", 3, { epTabRow, epTabHead, epDefEntry }},
 { "topic/draft-comment", 4, { epText, epInline, epDraft, epPern }},
 { "map/topicref bookmap/draftintro", 3, { epMap, epRef, epTopic }},
 { "topic/dt", 3, { epText, epTabCell, epDefTerm }},
 { "topic/dthd", 3, { epText, epTabCell, epDefTerm }},
 { "topic/data bookmap/edited", 0, NULL},
 { "topic/data bookmap/edition", 0, NULL},
 { "topic/entry", 3, { epText, epTabCell, epPern }},
 { "topic/example", 4, { epTask, epText, epSect, epPern }},
 { "topic/featnum", 2, { epText, epVar }},
 { "topic/fig", 1, { epFig }},
 { "topic/figgroup", 0, NULL},
 { "map/topicref bookmap/figurelist", 4, { epMap, epRef, epTopic, epList }},
 { "topic/ph sw-d/filepath", 2, { epText, epInline }},
 { "topic/fn", 5, { epText, epInline, epFtn, epNumbered, epXRsrc }},
 { "topic/foreign", 1, { epInline }},
 { "topic/figgroup pr-d/fragment", 0, NULL},
 { "topic/xref pr-d/fragref", 1, { epText }},
 { "map/topicref bookmap/frontmatter", 2, { epMap, epList }},
 { "map/topicref bookmap/glossarylist", 5, { epMap, epRef, epTopic, epList, epGloss }},
 { "topic/abstract concept/abstract glossentry/glossdef", 3, { epText, epAbstr, epGloss }},
 { "topic/topic concept/concept glossentry/glossentry", 2, { epRoot, epGloss }},
 { "topic/topic concept/concept glossgroup/glossgroup", 1, { epRoot }},  // *
 { "map/topicref glossref-d/glossref ", 4, { epMap, epRef, epTopic, epGloss }},  // *
 { "topic/title concept/title glossentry/glossterm", 4, { epText, epTitle, epXRsrc, epGloss }},
 { "topic/figgroup pr-d/groupchoice", 0, NULL},
 { "topic/figgroup pr-d/groupcomp", 0, NULL},
 { "topic/figgroup pr-d/groupseq", 0, NULL},
 { "topic/ph hi-d/i", 3, { epText, epInline, epTypo }},
 { "topic/image", 2, { epInline, epImage }},
 { "topic/fig ut-d/imagemap", 5, { epFig, epInline, epImage, epRef, epGroup }},
 { "topic/index-base", 3, { epText, epInline, epIndex }},
 { "topic/index-base indexing-d/index-see", 4, { epText, epInline, epIndex, epIndexSee }},
 { "topic/index-base indexing-d/index-see-also", 4, { epText, epInline, epIndex, epIndexSeeAlso }},
 { "topic/index-base indexing-d/index-sort-as", 4, { epText, epInline, epIndex, epIndexSort }},
 { "map/topicref bookmap/indexlist", 4, { epMap, epRef, epTopic, epList }},
 { "topic/indexterm", 4, { epText, epInline, epIndex, epStart }},
 { "topic/indextermref", 2, { epInline, epIndex }},
 { "topic/itemgroup task/info", 3, { epTask, epText, epPern }},
 { "topic/data bookmap/isbn", 3, { epText, epMap, epVar }},
 { "topic/itemgroup", 2, { epText, epPern }},
 { "map/topicref mapgroup-d/keydef", 4, { epKey, epMap, epRef, epTopic }},
 { "topic/keyword", 2, { epText, epInline }},
 { "topic/keywords", 0, NULL},
 { "topic/keyword pr-d/kwd", 1, { epText }},
 { "topic/li", 4, { epText, epListItem, epXRsrc, epPern }},
 { "topic/lines", 2, { epText, epPre }},
 { "topic/link", 1, { epLink }},
 { "topic/linkinfo", 3, { epLink, epText, epSeq }},
 { "topic/linklist", 3, { epLink, epList, epSeq }},
 { "topic/linkpool", 2, { epLink, epList }},
 { "map/linktext", 3, { epLink, epText, epMap }},
 { "topic/linktext", 2, { epLink, epText }},
 { "topic/longdescref", 2, { epInline, epRef }},  // *
 { "topic/longquoteref", 2, { epInline, epRef }},  // *
 { "topic/lq", 2, { epText, epQuote }},
 { "topic/ph bookmap/mainbooktitle", 4, { epText, epMap, epVar, epBkTitle }},
 { "topic/data bookmap/maintainer", 0, NULL},
 { "map/map", 2, { epRoot, epMap }},
 { "map/topicref mapgroup-d/mapref", 3, { epMap, epRef, epTopic }},
 { "topic/ph ui-d/menucascade", 2, { epInline, epCascadeSet }},
 { "topic/metadata", 0, NULL},
 { "topic/ph bookmap/month", 3, { epText, epMap, epInline }},
 { "topic/pre sw-d/msgblock", 2, { epText, epPre }},
 { "topic/keyword sw-d/msgnum", 2, { epText, epInline }},
 { "topic/ph sw-d/msgph", 2, { epText, epInline }},
 { "map/navref", 0, NULL},
 { "topic/navtitle", 2, { epText, epNavtitle }},
 { "topic/no-topic-nesting", 0, NULL},
 { "topic/note", 2, { epText, epNote }},
 { "map/topicref bookmap/notices", 3, { epMap, epRef, epTopic }},
 { "topic/object", 2, { epObj }},
 { "topic/ol", 2, { epList, epNumbered }},
 { "topic/ph pr-d/oper", 1, { epText }},
 { "topic/keyword pr-d/option", 2, { epText, epInline }},
 { "topic/data bookmap/organization", 1, { epMap }},
 { "topic/othermeta", 0, NULL},
 { "topic/p", 2, { epText, epPern }},
 { "topic/param", 2, { epObj, epParam }},
 { "topic/dl pr-d/parml", 3, { epTable, epStart, epParmList }},
 { "topic/keyword pr-d/parmname", 2, { epText, epInline }},
 { "map/topicref bookmap/part", 3, { epMap, epRef, epTopic }},
 { "topic/dd pr-d/pd", 3, { epText, epTabCell, epParmDef }},
 { "topic/permissions", 0, NULL},
 { "topic/data bookmap/person", 1, { epMap }},
 { "topic/ph", 2, { epText, epInline }},
 { "topic/platform", 2, { epText, epVar }},
 { "topic/dlentry pr-d/plentry", 3, { epTabRow, epTabBody, epParmEntry }},
 { "topic/section task/postreq", 3, { epTask, epText, epSect }},
 { "topic/pre", 2, { epText, epPre }},
 { "map/topicref bookmap/preface", 3, { epMap, epRef, epTopic }},
 { "topic/section task/prereq", 3, { epTask, epText, epSect }},
 { "topic/data bookmap/printlocation", 1, { epMap }},
 { "topic/prodinfo", 0, NULL},
 { "topic/prodname", 2, { epText, epVar }},
 { "topic/prognum", 2, { epText, epVar }},
 { "topic/prolog",  2, { epMeta, epGroup }},
 { "topic/stentry reference/propdesc", 3, { epText, epTabCell, epRefer }},
 { "topic/stentry reference/propdeschd", 3, { epText, epTabCell, epRefer }},
 { "topic/simpletable reference/properties", 3, { epTable, epStart, epRefer }},
 { "topic/strow reference/property", 3, { epTabRow, epTabBody, epRefer }},
 { "topic/sthead reference/prophead", 3, { epTabRow, epTabHead, epRefer }},
 { "topic/stentry reference/proptype", 3, { epText, epTabCell, epRefer }},
 { "topic/stentry reference/proptypehd", 3, { epText, epTabCell, epRefer }},
 { "topic/stentry reference/propvalue", 3, { epText, epTabCell, epRefer }},
 { "topic/stentry reference/propvaluehd", 3, { epText, epTabCell, epRefer }},
 { "topic/dt pr-d/pt", 3, { epText, epTabCell, epParmTerm }},
 { "topic/data bookmap/published", 1, { epMap }},
 { "topic/publisher", 2, { epText, epVar }},
 { "topic/publisher bookmap/publisherinformation", 3, { epMap, epText, epVar }},
 { "topic/data bookmap/publishtype", 1, { epMap }},
 { "topic/q", 4, { epText, epInline, epTypo, epQuote }},
 { "topic/body reference/refbody", 2, { epText, epPern }},
 { "topic/bodydiv reference/refbodydiv", 4, { epText, epSect, epNolev, epRefer }},  // *
 { "topic/topic reference/reference", 2, { epRoot, epRefer }},
 { "topic/section reference/refsyn", 3, { epText, epSect, epRefer }},
 { "topic/related-links", 1, { epRel }},
 { "map/relcell", 1, { epTabCell }},
 { "map/relcolspec", 2, { epTable, epTabCol }},
 { "map/relheader", 2, { epTabRow, epTabHead }},
 { "map/relrow", 2, { epTabRow, epTabBody }},
 { "map/reltable", 4, { epMap, epTable, epStart, epRel }},
 { "topic/ph pr-d/repsep", 1, { epText }},
 { "topic/required-cleanup", 1, { epInline }},
 { "topic/resourceid", 2, { epRefer, epMeta }},
 { "topic/section task/result", 3, { epTask, epText, epSect }},
 { "topic/data bookmap/reviewed", 1, { epMap }},
 { "topic/revised", 0, NULL},
 { "topic/ph bookmap/revisionid", 3, { epText, epMap, epInline }},
 { "topic/row", 1, { epTabRow }},
 { "topic/pre ui-d/screen", 2, { epText, epPre }},
 { "map/searchtitle", 2, { epText, epMap }},
 { "topic/searchtitle", 1, { epText }},
 { "topic/section", 3, { epText, epSect, epPern }},
 { "topic/sectiondiv", 3, { epText, epSect, epNolev }},  // *
 { "topic/ph pr-d/sep", 1, { epText }},
 { "topic/series", 2, { epText, epVar }},
 { "topic/keyword ut-d/shape", 2, { epText, epImage }},
 { "topic/keyword ui-d/shortcut", 2, { epText, epInline }},
 { "map/shortdesc", 3, { epText, epSDesc, epMap }},
 { "topic/shortdesc", 2, { epText, epSDesc }},
 { "topic/simpletable", 2, { epTable, epStart }},
 { "topic/sl", 1, { epList }},
 { "topic/sli", 2, { epText, epListItem }},
 { "topic/source", 2, { epText, epVar }},
 { "topic/ph bookmap/started", 3, { epText, epMap, epInline }},
 { "topic/state", 1, { epInline }},
 { "topic/stentry", 2, { epText, epTabCell }},
 { "topic/li task/step", 5, { epTask, epText, epListItem, epXRsrc, epPern }},
 { "topic/itemgroup task/stepresult", 3, { epTask, epText, epPern }},
 { "topic/ol task/steps", 3, { epTask, epList, epNumbered }},
 { "topic/section task/steps-informal", 3, { epText, epSect, epTask }},  // *
 { "topic/ul task/steps-unordered", 2, { epTask, epList }},
 { "topic/li task/stepsection", 5, { epTask, epText, epListItem, epNonum, epPern }},  // *
 { "topic/itemgroup task/stepxmp", 3, { epTask, epText, epPern }},
 { "topic/sthead", 2, { epTabRow, epTabHead }},
 { "topic/strow", 2, { epTabRow, epTabBody }},
 { "topic/ph hi-d/sub", 3, { epText, epInline, epTypo }},
 { "topic/li task/substep", 5, { epTask, epText, epListItem, epXRsrc, epPern }},
 { "topic/ol task/substeps", 4, { epTask, epList, epNumbered, epSub }},
 { "topic/ph bookmap/summary", 3, { epText, epMap, epInline }},
 { "topic/ph hi-d/sup", 3, { epText, epInline, epTypo }},
 { "topic/figgroup pr-d/synblk", 0, NULL},
 { "topic/fn pr-d/synnote", 1, { epText }},
 { "topic/xref pr-d/synnoteref", 0, NULL},
 { "topic/ph pr-d/synph", 2, { epText, epInline }},
 { "topic/fig pr-d/syntaxdiagram", 1, { epInline }},
 { "topic/ph sw-d/systemoutput", 2, { epText, epInline }},
 { "topic/table", 2, { epTable, epStart }},
 { "map/topicref bookmap/tablelist", 4, { epMap, epRef, epTopic, epList }},
 { "topic/topic task/task", 2, { epRoot, epTask }},
 { "topic/body task/taskbody", 2, { epText, epPern }},  // *
 { "topic/tbody", 2, { epTable, epTabBody }},
 { "topic/term", 3, { epText, epInline, epGloss }},
 { "topic/data bookmap/tested", 1, { epMap }},
 { "topic/text", 2, { epText, epInline }},
 { "topic/tgroup", 1, { epTable }},
 { "topic/thead", 2, { epTable, epTabHead }},
 { "topic/title", 3, { epText, epTitle, epXRsrc }},
 { "topic/titlealts", 0, NULL},
 { "topic/tm", 3, { epText, epInline, epTmark }},
 { "map/topicref bookmap/toc", 4, { epMap, epRef, epTopic, epList }},
 { "topic/topic", 1, { epRoot }},
 { "map/topicref mapgroup-d/topicgroup", 4, { epMap, epGroup, epTopic, epNolev }},
 { "map/topicref mapgroup-d/topichead", 2, { epMap, epTopic }},
 { "map/topicmeta", 3, { epMap, epMeta, epTopic }},
 { "map/topicref", 3, { epMap, epRef, epTopic }},
 { "map/topicref mapgroup-d/topicset", 3, { epMap, epRef, epTopic }},
 { "map/topicref mapgroup-d/topicsetref", 3, { epMap, epRef, epTopic }},
 { "map/topicref bookmap/trademarklist", 4, { epMap, epRef, epTopic, epList }},
 { "topic/ph hi-d/tt", 2, { epText, epInline }},
 { "topic/itemgroup task/tutorialinfo", 3, { epTask, epText, epPern }},
 { "topic/ph hi-d/u", 3, { epText, epInline, epTypo }},
 { "topic/ph ui-d/uicontrol", 3, { epText, epInline, epCascadeItem }},
 { "topic/ul", 1, { epList }},
 { "topic/unknown", 1, { epInline }},
 { "topic/ph sw-d/userinput", 2, { epText, epInline }},
 { "topic/ph pr-d/var", 1, { epText }},
 { "topic/keyword sw-d/varname", 2, { epText, epInline }},
 { "topic/data bookmap/volume", 1, { epMap }},
 { "topic/vrm", 0, NULL},
 { "topic/vrmlist", 0, NULL},
 { "topic/keyword ui-d/wintitle", 2, { epText, epInline }},
 { "topic/xref", 3, { epText, epInline, epRef }},
 { "topic/ph bookmap/year", 3, { epText, epMap, epInline }}
};


DCnlist XMLrd::EpNames;

npair XMLrd::EpNameInit[] = {
 { epRoot, "Root" },
 { epMap, "Map" },
 { epTopic, "Topic" },
 { epTask, "Task" },
 { epMeta, "Meta" },
 { epText, "Text" },
 { epInline, "Inline" },
 { epPern, "Pernicious" },
 { epPre, "Pre" },
 { epTypo, "Typo" },
 { epTitle, "Title" },
 { epBkTitle, "BookTitle" },
 { epSect, "Section" },
 { epFig, "Fig" },
 { epImage, "Image" },
 { epObj, "Object" },
 { epAlt, "Alt" },
 { epParam, "Param" },
 { epTable, "Table" },
 { epTabRow, "TabRow" },
 { epTabCol, "TabCol" },
 { epTabCell, "TabCell" },
 { epTabHead, "TabHead" },
 { epTabBody, "TabBody" },
 { epStart, "Start" },
 { epStart, "TabStart" },
 { epLink, "Link" },
 { epKey, "Key" },
 { epRef, "Ref" },
 { epRel, "Rel" },
 { epXRsrc, "XRSource" },
 { epGroup, "Group" },
 { epSeq, "Sequence" },
 { epList, "List" },
 { epListItem, "ListItem" },
 { epNumbered, "Num" },
 { epDefList, "DList" },
 { epDefEntry, "DLEntry" },
 { epDefTerm, "DLTerm" },
 { epDefDef, "DLDef" },
 { epParmList, "PList" },
 { epParmEntry, "PLEntry" },
 { epParmTerm, "PLTerm" },
 { epParmDef, "PLDef" },
 { epNote, "Note" },
 { epIndex, "Index" },
 { epIndexStart, "IxStart" },
 { epIndexSee, "IxSee" },
 { epIndexSeeAlso, "IxAlso" },
 { epIndexSort, "IxSort" },
 { epFtn, "Footnote" },
 { epDesc, "Desc" },
 { epNavtitle, "Navtitle" },
 { epSDesc, "SDesc" },
 { epAbstr, "Abstr" },
 { epVar, "Var" },
 { epRefer, "Reference" },
 { epGloss, "Glossary" },
 { epData, "Data" },
 { epCascadeItem, "CascadeItem" },
 { epCascadeSet, "CascadeSet" },
 { epSub, "Sub" },
 { epTmark, "Trademark" },
 { epAbbr, "Abbrev" },  // *
 { epNonum, "NoNumber" },  // *
 { epNolev, "NoLevel" },  // *
 { epDraft, "Draft" },  // *
 NULL
};


// end of drxmldt.cpp

